### ISSUE TITLE
"docs" space isn't deleted on `catkin clean`

### ISSUE THREAD

**Issue by mikepurvis** [mikepurvis/catkin_tools_document#3]
Because documentation is a new verb rather than a new build type, I don't think this is fixable without an additional hook from catkin_tools. Basically, there would need to be a way to register a new "space" with catkin_tools. This would actually be great for a couple reasons:

- It would allow it to be tracked and cleaned properly, as in this ticket.
- It would make the new space a first-class member of the [Context object](https://github.com/catkin/catkin_tools/blob/2442e1f971ae6bbd0c14fa6da183ee095ae099e3/catkin_tools/context.py#L40), whereas right now the "docs space" is kind of goofily placed at `$build_space/../docs`.
- It would allow the user to explicitly set the location of the docs space, similar to how the other spaces can be set with `catkin config`.

Thoughts on this, @wjwwood?

**Comment by wjwwood** [comment]
That sounds great to me. There are potentially lots of places where `catkin_tools` could be extended externally, but adding those extension points as needed seems like a fine way to approach the issue. Specifically for adding spaces or adding a doc space, I can't think of any issues with doing that off-hand.

However, I'd suggest using `doc` as the folder name and refer to it as the `doc space`, since all of the other folder/spaces are singular already (except `logs` which I would have changed if I had noticed at the time).

+1 for adding spaces by extension.

**Comment by mikepurvis** [comment]
Interesting point on plural/singular. "Docs" does feel more natural do me, as would "tests" or "test_results" for a test verb. I think there is an internal kind of consistency in the way it is, in the sense that you do only have _one_ build, and _one_ install result, but each build produces _many_ log files of output.

Either way, I'll mull over some thoughts about a new extension point, and maybe put up a PR at some point.

**Comment by mikepurvis** [comment]
Yup, thanks!
